# Generated by Django 2.2.3 on 2019-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
