# Generated by Django 2.2.3 on 2019-07-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_menumodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='button_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='button_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headermodel',
            name='background_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infomodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
