# Generated by Django 2.2.3 on 2019-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_auto_20190704_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='background_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
