# Generated by Django 2.2.3 on 2019-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_menumodel_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='button',
            field=models.CharField(max_length=20),
        ),
    ]
