# Generated by Django 2.2.3 on 2019-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_auto_20190704_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='button_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
