# Generated by Django 2.2.3 on 2019-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_auto_20190704_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='button',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='button_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
