# Generated by Django 2.2.3 on 2019-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_aboutmodel_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='button_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
