# Generated by Django 2.2.3 on 2019-07-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_contactmodel_button_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='text',
        ),
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.ContactModel')),
            ],
        ),
    ]
