# Generated by Django 2.2.3 on 2019-07-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0015_remove_contactmodel_button_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmodel',
            name='contact_id',
        ),
    ]
