# Generated by Django 2.2.3 on 2019-07-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0017_auto_20190704_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmodel',
            old_name='mail',
            new_name='email',
        ),
    ]
