# Generated by Django 2.2.3 on 2019-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0018_auto_20190705_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='icon',
        ),
    ]
