# Generated by Django 2.2.3 on 2019-07-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0019_auto_20190705_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconmodel',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.InfoModel'),
        ),
    ]
