# Generated by Django 2.2.3 on 2019-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0021_auto_20190705_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermodel',
            name='copyright',
            field=models.CharField(max_length=50),
        ),
    ]
