# Generated by Django 2.2.3 on 2019-07-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0022_auto_20190705_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
