# Generated by Django 2.2.3 on 2019-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0023_contactformmodel_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
