# Generated by Django 2.2.3 on 2019-07-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0024_portfoliomodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_bg', models.CharField(blank=True, max_length=50, null=True)),
                ('header_bg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('header_avatar', models.ImageField(upload_to='media/')),
                ('header_title', models.CharField(max_length=50)),
                ('header_subtitle', models.CharField(max_length=50)),
                ('portfolio_name', models.CharField(max_length=50)),
                ('about_name', models.CharField(blank=True, max_length=20, null=True)),
                ('about_btn_link', models.CharField(blank=True, max_length=500, null=True)),
                ('about_btn', models.CharField(blank=True, max_length=20, null=True)),
                ('about_bg', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_btn', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_btn_color', models.CharField(blank=True, max_length=50, null=True)),
                ('footer_bg', models.TextField(blank=True, null=True)),
                ('copyright', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.DeleteModel(
            name='FooterModel',
        ),
        migrations.DeleteModel(
            name='HeaderModel',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='button',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menumodel',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='name',
        ),
    ]
