# Generated by Django 2.2.3 on 2019-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0025_auto_20190706_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqemodel',
            name='header_bg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
