# Generated by Django 2.2.3 on 2019-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0027_auto_20190706_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='caption',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
