# Generated by Django 2.2.3 on 2019-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0028_portfoliomodel_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
