# Generated by Django 2.2.3 on 2019-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0030_auto_20190706_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
